version: '3'
services:

  db:
    image: mdillon/postgis
    restart: always
    volumes:
     - pgdata:/var/lib/postgresql/data
     
  emstrack:
    build:
      context: .
    ports:
     - "8000:8000"
     - "1883:1883"
     - "8883:8883"
     - "8884:8884"
    volumes:
     - settings:/etc/emstrack
    tty: true

volumes:
  pgdata:
  settings:
