version: '3'
services:

  db:
    image: postgis:10-2.5
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
     - pgdata:/var/lib/postgresql/data
     
  emstrack:
    build:
      context: .
    ports:
     - "1883:1883"
     - "8000:8000"
     - "8883:8883"
     - "8884:8884"
    volumes:
     - settings:/etc/emstrack
    tty: true

volumes:
  pgdata:
  settings:
