version: '3'
services:

  db:
    image: postgis:10-2.5
    restart: always
    environment:
      POSTGRES_PASSWORD: password

  emstrack:
    build:
      context: .
      args:
        BRANCH: "master"
    ports:
     - "1883:1883"
     - "8000:8000"
     - "8883:8883"
     - "8884:8884"
    volumes:
     - certificates:/etc/certificates
    tty: true

volumes:
  certificates:
