version: '3'
services:

  db:
    image: mdillon/postgis
    restart: always
    volumes:
     - pgdata:/var/lib/postgresql/data
     
  emstrack:
    build:
      context: .
    env_file:
      - settings.env
      - local.env
    ports:
     - "8000:8000"
     - "1883:1883"
     - "8883:8883"
     - "8884:8884"
    volumes:
     - settings:/etc/emstrack
     - nginx:/etc/nginx
     - logs:/var/log
    tty: true

volumes:
  pgdata:
  settings:
  nginx:
  logs:
